### ISSUE TITLE
Crash when using nette lower then 2.3.0

### ISSUE THREAD

**Issue by Salamek** [drahak/Restful#108]
Readme says nette 2.0.x ...

Crash message:
`Service 'router': Expected class, method or property, Nette\PhpGenerator\Helpers::createObject('Nette\DI\Statement', array( "\x00Nette\\DI\\Statement\x00entity" => 'offsetSet', 'arguments' => array( NULL, Nette\PhpGenerator\Helpers::createObject('Nette\DI\Statement', array( "\x00Nette\\DI\\Statement\x00entity" => '@restful.cachedRouteListFactory::create', 'arguments' => array(), )), ), )) given`

Restful config

```
extensions:
  restful: Drahak\Restful\DI\RestfulExtension

restful:
    convention: 'camelCase'
    cacheDir: '%tempDir%/cache'
    jsonpKey: 'jsonp'
    prettyPrintKey: 'pretty'
    routes:
        generateAtStart: False
        prefix: api
        module: 'RestApi'
        autoGenerated: True
        panel: True
    security:
        privateKey: 'my-secret-api-key'
        requestTimeKey: 'timestamp'
        requestTimeout: 300
```
